name: Push New or Renamed MD Files to Another Repository

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-new-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        

      - name: Clone target repository
        run: git clone https://github.com/matze2402/matze2402.git matze2402

      - name: Identify new or renamed MD files
        id: new-or-renamed-md-files
        run: |
          cd fin
          # Check the status of files after changes
          all_md_files=$(ls *.md)
          git add .
          changed_md_files=$(git status --porcelain | grep '^R\|^A' | grep '\.md$' | cut -c4-)
          echo "::set-output name=changed_md_files::$changed_md_files"
          echo "::set-output name=all_md_files::$all_md_files"

      - name: Copy new or renamed MD files to target repository
        run: |
          changed_md_files="${{ steps.new-or-renamed-md-files.outputs.changed_md_files }}"
          all_md_files="${{ steps.new-or-renamed-md-files.outputs.all_md_files }}"
          # Check if the file is new or renamed
          for file in $changed_md_files; do
            if [[ $all_md_files =~ $file ]]; then
              cp "myyyy/fin/$file" "matze2402/destination_folder/$file"
            fi
          done

      - name: Commit and push new or renamed MD files to target repository
        if: steps.new-or-renamed-md-files.outputs.changed_md_files != ''
        run: |
          cd matze2402
          git config --local user.email "action@github.com"
          git config --local user.name "Matze2402"
          git config --global url.https://${{ secrets.token}}@github.com/.insteadOf https://github.com/
          git add destination_folder
          git commit -m "Add new or renamed MD files from source repository"
          git push
