name: Push New MD Files to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push-new-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          path: myyyy

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: matze2402/matze2402
          path: matze2402
          ref: main  # Specify the branch of the target repository

      - name: Identify new MD files
        id: new-md-files
        run: |
          cd myyyy/fin
          for file in *.md; do
            if [ ! -f "../../matze2402/destination_folder/$file" ]; then
              echo "$file" >> ../../new_md_files.txt
            fi
          done

      - name: Copy new MD files to target repository
        run: |
          while IFS= read -r file; do
            cp "myyyy/fin/$file" "matze2402/destination_folder/$file"
          done < fin/new_md_files.txt

      - name: Commit and push new MD files to target repository
        if: steps.new-md-files.outputs.stdout != ''
        run: |
          cd matze2402
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.token}}@github.com/.insteadOf https://github.com/
          git add destination_folder
          git commit -m "Add new MD files from source repository"
          git push
