name: Push New MD Files to Another Repository

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-new-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: matze2402/myyyy 
          path: source_repo

      - name: Clone target repository
        run: |
          git clone https://github.com/matze2402/matze2402.git matze2402
          mkdir -p ../matze2402/destination_folder  # Create destination_folder if it doesn't exist
          touch matze2402/destination_folder/pushed_files.txt  # Create pushed_files.txt if it doesn't exist

      - name: Identify new MD files
        id: new-md-files
        run: |
          new_md_files=""
          cd source_repo/fin
          for file in *.md; do
            # Check if the file has been pushed to the target repository before
           sanitized_file=$(echo "$file" | sed 's/^"//' | sed 's/"$//')
if ! grep -q "^$sanitized_file$" "$(curl -sSL "https://raw.githubusercontent.com/matze2402/matze2402/main/destination_folder/pushed_files.txt")"; then

              new_md_files="$new_md_files $file"
            fi
          done
          echo "::set-output name=new_md_files::$new_md_files"

      - name: Copy new MD files to target repository
        run: |
          new_md_files="${{ steps.new-md-files.outputs.new_md_files }}"
          cd source_repo/fin
          for file in $new_md_files; do
            cp "$file" "../destination_folder/$file"
          done

      - name: Record pushed files
        if: steps.new-md-files.outputs.new_md_files != ''
        run: |
          new_md_files="${{ steps.new-md-files.outputs.new_md_files }}"
          for file in $new_md_files; do
            echo "$file" >> "../../matze2402/destination_folder/pushed_files.txt"
          done

      - name: Commit and push new MD files to target repository
        if: steps.new-md-files.outputs.new_md_files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.new }}
        run: |
          cd matze2402
          git config --local user.email "action@github.com"
          git config --local user.name "Matze2402"
          git config --global url.https://${{ secrets.token}}@github.com/.insteadOf https://github.com/
          git add destination_folder
          git commit -m "Add new MD files from source repository"
          git push
